// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Back.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240820141757_ModelsCreate")]
    partial class ModelsCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.21");

            modelBuilder.Entity("Back.Models.ComentarioModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PostagemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PostagemModelid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("conteudo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("PostagemModelid");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("Back.Models.PostagemModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("conteudo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Postagens");
                });

            modelBuilder.Entity("Back.Models.ComentarioModel", b =>
                {
                    b.HasOne("Back.Models.PostagemModel", null)
                        .WithMany("Comentarios")
                        .HasForeignKey("PostagemModelid");
                });

            modelBuilder.Entity("Back.Models.PostagemModel", b =>
                {
                    b.Navigation("Comentarios");
                });
#pragma warning restore 612, 618
        }
    }
}
